/**
 * SourceApi
 * A Web API for controlling a source.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIZenuxLogsApiHandler_H
#define OAI_OAIZenuxLogsApiHandler_H

#include <QObject>

namespace OpenAPI {

class OAIZenuxLogsApiHandler : public QObject
{
    Q_OBJECT

public:
    OAIZenuxLogsApiHandler();
    virtual ~OAIZenuxLogsApiHandler();


public slots:
    virtual void logsGet();
    
private:
    QString getDeviceName();

};

}

#endif // OAI_OAIZenuxLogsApiHandler_H
