/**
 * SourceApi
 * A Web API for controlling a source.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>
#include <QFile>

#include "OAIZenuxLogsApiHandler.h"
#include "OAIZenuxLogsApiRequest.h"

namespace OpenAPI {

OAIZenuxLogsApiHandler::OAIZenuxLogsApiHandler(){

}

OAIZenuxLogsApiHandler::~OAIZenuxLogsApiHandler(){

}

void OAIZenuxLogsApiHandler::logsGet()
{
    auto reqObj = qobject_cast<OAIZenuxLogsApiRequest*>(sender());
    if( reqObj != nullptr ) {
        QHttpEngine::Socket *socket = reqObj->getRawSocket();
        QString fileName = "/tmp/" + getDeviceName() + ".zip";
        QFile file(fileName);
        if (!file.open(QIODevice::ReadOnly)) {
            socket->setStatusCode(QHttpEngine::Socket::NotFound);
            socket->write("File not found");
            socket->close();
            return;
        }
        QByteArray data = file.readAll();
        socket->setHeader("Content-Type", "application/zip");
        socket->setHeader("Content-Disposition",
                          "attachment; filename=\"" + getDeviceName().toUtf8() + ".zip\"");
        socket->setHeader("Content-Length",
                          QByteArray::number(data.size()));

        socket->write(data);
        socket->close();
    }
}

QString OAIZenuxLogsApiHandler::getDeviceName()
{
    QFile file("/etc/hostname");
    if(!file.open(QFile::ReadOnly))
        return QString();
    return file.readAll().replace("\n", "");
}
}
